name: Rubiks_cube
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.11
  - pip=23.2.1
  - python=3.10.13
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - aiosignal==1.3.1
      - astunparse==1.6.3
      - attrs==23.1.0
      - cachetools==5.3.1
      - certifi==2023.5.7
      - cfgv==3.4.0
      - charset-normalizer==3.2.0
      - click==8.1.5
      - cloudpickle==2.2.1
      - cmake==3.26.4
      - distlib==0.3.7
      - dm-tree==0.1.8
      - farama-notifications==0.0.4
      - filelock==3.12.2
      - flatbuffers==23.5.26
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gast==0.4.0
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.51.3
      - gymnasium==0.29.0
      - gymnasium-notices==0.0.1
      - h5py==3.9.0
      - identify==2.5.29
      - idna==3.4
      - imageio==2.31.1
      - jax-jumpy==1.0.0
      - jinja2==3.1.2
      - jsonschema==4.18.3
      - jsonschema-specifications==2023.6.1
      - keras==2.13.1
      - lazy-loader==0.3
      - libclang==16.0.6
      - lit==16.0.6
      - lz4==4.3.2
      - markdown==3.4.3
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.0.5
      - networkx==3.1
      - nodeenv==1.8.0
      - numpy
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.1
      - pandas==2.0.3
      - pillow==10.0.0
      - platformdirs==3.10.0
      - pre-commit==3.4.0
      - protobuf==4.23.4
      - pyarrow==12.0.1
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pygame==2.5.0
      - pygments==2.15.1
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pywavelets==1.4.1
      - pyyaml==6.0
      - ray==2.5.1
      - referencing==0.29.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rich==13.4.2
      - rpds-py==0.8.10
      - rsa==4.9
      - scikit-image==0.21.0
      - scipy==1.11.1
      - six==1.16.0
      - sympy==1.12
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tensorboardx==2.6.1
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.32.0
      - termcolor==2.3.0
      - tifffile==2023.7.10
      - torch==2.0.1
      - triton==2.0.0
      - typer==0.9.0
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - urllib3==1.26.16
      - virtualenv==20.24.5
      - werkzeug==2.3.6
      - wrapt==1.15.0
